apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: immich-catalog
spec:
  images:
    # Immich v3 requires the VectorChord extension (pgvecto.rs is deprecated)
    - image: "ghcr.io/tensorchord/cloudnative-vectorchord:16.14-1.1.1@sha256:4a26ca6aad2482289f4a3d3317ccbf1439ce3de140994598375a1f4c4e2e9f8d"
      major: 16
