apiVersion: batch/v1
kind: Job
metadata:
  name: immich-secret-init
  namespace: immich
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      serviceAccountName: setup-sa
      containers:
        - name: secret-gen
          image: docker.io/alpine/k8s:1.36.2
          command:
            - /bin/bash
            - -c
            - |
              set -e
              if ! kubectl get secret immich-admin-creds -n immich >/dev/null 2>&1; then
                echo "Generating Immich password..."
                PASSWORD=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)
                ADMIN_EMAIL=$(kubectl get cm smallworlds-global-config -n default -o jsonpath='{.data.ADMIN_EMAIL}')
                
                kubectl create secret generic immich-admin-creds -n immich \
                  --from-literal=email="$ADMIN_EMAIL" \
                  --from-literal=password="$PASSWORD" \
                  --from-literal=name="SmallWorlds Admin"
              else
                echo "immich-admin-creds already exists, skipping."
              fi
      restartPolicy: OnFailure
