apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: immich
type: Opaque
# These are placeholder values. You will need to replace them with your actual Keycloak client secret once configured in the UI.
# Use `echo -n "YOUR_SECRET" | base64` to get the base64 encoded values.
data:
  # Base64 encoded 'client-secret'
  client-secret: ZjNiNzdjMWMxNzhiMGUwMDgzYjFhYzczN2RjODlmZTA5YzU1ODQ3ODRiNGQxYTA3MGU1YTI1M2FjMTU0Y2EzZQ==
