apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich

bases:
  - ../../bases/setup-rbac
  - ../../bases/redis
  - ../../bases/cnpg-cluster
  - ../../bases/garage-init-job
  - ../../bases/keycloak-client-job

resources:
  - admin-init-job.yaml
  - immich-secret-init-job.yaml
  - library-pvc.yaml
  - immich-catalog.yaml

patches:
  - target:
      kind: ClusterRoleBinding
      name: setup-binding
    patch: |-
      - op: replace
        path: /metadata/name
        value: setup-binding-immich
  - target:
      kind: Job
      name: keycloak-client-init
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: REDIRECT_URIS
            value: '["https://photos.smallworlds.network/auth/login", "https://photos.smallworlds.network/user-settings", "app.immich:///"]'
  - target:
      kind: Cluster
      name: database
    patch: |-
      - op: remove
        path: /spec/imageName
      - op: add
        path: /spec/imageCatalogRef
        value:
          apiGroup: postgresql.cnpg.io
          kind: ClusterImageCatalog
          name: immich-catalog
          major: 16
      - op: add
        path: /spec/bootstrap/initdb/postInitSQL
        value:
          - CREATE EXTENSION IF NOT EXISTS vectors;
          - CREATE EXTENSION IF NOT EXISTS cube;
          - CREATE EXTENSION IF NOT EXISTS earthdistance;

      - op: add
        path: /spec/postgresql
        value:
          shared_preload_libraries:
            - "vectors.so"
  - target:
      kind: Deployment
      name: immich-server
    patch: |-
      - op: replace
        path: /spec/template/spec/enableServiceLinks
        value: false
  - target:
      kind: Deployment
      name: immich-machine-learning
    patch: |-
      - op: replace
        path: /spec/template/spec/enableServiceLinks
        value: false

helmCharts:
  - name: immich
    repo: https://immich-app.github.io/immich-charts
    releaseName: immich
    version: 0.8.0
    valuesFile: values.yaml
