apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: immich
spec:
  storageClassName: hetzner-local
  volumeName: immich-library-pv    # binds to the Hetzner-backed PV defined in persistent-storage.yaml
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
