apiVersion: v1
kind: ServiceAccount
metadata:
  name: immich-setup-sa
  namespace: immich
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: immich-setup-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "patch", "apply", "update"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: immich-setup-binding
subjects:
  - kind: ServiceAccount
    name: immich-setup-sa
    namespace: immich
roleRef:
  kind: ClusterRole
  name: immich-setup-role
  apiGroup: rbac.authorization.k8s.io
