controllers:
  main:
    containers:
      main:
        image:
          tag: v2.5.6
        env:
          DB_DATABASE_NAME: immich
          DB_HOSTNAME: immich-db-rw
          DB_USERNAME: immich
          REDIS_HOSTNAME: immich-redis
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-db-app
                key: password
          IMMICH_OAUTH_CLIENT_SECRET:
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: client-secret
valkey:
  enabled: false
server:
  enabled: true
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: photos.smallworlds.network
          paths:
            - path: "/"
      tls:
        - secretName: immich-tls
          hosts:
            - photos.smallworlds.network
machine-learning:
  enabled: true
immich:
  configuration:
    oauth:
      enabled: true
      issuerUrl: https://identity.smallworlds.network/realms/smallworlds
      clientId: immich
      autoRegister: true
      autoLaunch: true
      buttonText: Login with SmallWorlds ID
  persistence:
    library:
      existingClaim: immich-library-pvc
