env:
  DB_DATABASE_NAME: app
  DB_HOSTNAME: database-rw
  DB_USERNAME: app
  REDIS_HOSTNAME: redis
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: database-app
        key: password
  IMMICH_OAUTH_CLIENT_SECRET:
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: client-secret

postgresql:
  enabled: false
redis:
  enabled: false

server:
  enabled: true
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Photos"
        gethomepage.dev/description: "Immich"
        gethomepage.dev/group: "Applications"
        gethomepage.dev/icon: "immich.png"
      hosts:
        - host: photos.smallworlds.network
          paths:
            - path: "/"
      tls:
        - secretName: immich-tls
          hosts:
            - photos.smallworlds.network

machine-learning:
  enabled: true

immich:
  persistence:
    library:
      existingClaim: immich-library-pvc
