apiVersion: batch/v1
kind: Job
metadata:
  name: jitsi-secret-init
  namespace: jitsi
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      serviceAccountName: setup-sa
      containers:
        - name: secret-gen
          image: bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              set -e
              if ! kubectl get secret jitsi-jwt -n jitsi >/dev/null 2>&1; then
                echo "Generating Jitsi JWT app secret..."
                JWT_SECRET=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)

                kubectl create secret generic jitsi-jwt -n jitsi \
                  --from-literal=JWT_APP_SECRET="$JWT_SECRET"
              else
                echo "jitsi-jwt already exists, skipping."
              fi
      restartPolicy: OnFailure
