apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jitsi

helmCharts:
  - name: jitsi-meet
    repo: https://jitsi-contrib.github.io/jitsi-helm/
    releaseName: jitsi
    version: 2.20.0
    valuesFile: values.yaml

bases:
  - ../../bases/setup-rbac
  - ../../bases/keycloak-client-job

resources:
  - jitsi-secret-init-job.yaml

patches:
  - target:
      kind: ClusterRoleBinding
      name: setup-binding
    patch: |-
      - op: replace
        path: /metadata/name
        value: setup-binding-jitsi
  - target:
      kind: Job
      name: keycloak-client-init
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: REDIRECT_URIS
            value: '["https://meet.smallworlds.network/*"]'

