package hetznerprovision

import (
	"errors"
	"fmt"
	"sort"
	"strings"
)

// ErrInvalidBootstrap is returned when the cloud-init payload cannot be
// rendered from the given inputs.
var ErrInvalidBootstrap = errors.New("hetzner bootstrap payload is invalid")

// The readiness markers the node writes as each stage completes. Convergence is
// observed through these plus the live cluster state, so a node that rebooted
// mid-bootstrap reports what it actually finished rather than what it started.
// They match the markers the Local Cluster Node bootstrap writes, so one
// observation contract covers both deployment modes.
const (
	K3SReadyMarker     = "/etc/smallworlds/k3s-ready"
	ArgoCDReadyMarker  = "/etc/smallworlds/argocd-ready"
	OverlayReadyMarker = "/etc/smallworlds/overlay-applied"
)

// DataDirectory is where the persistent volume is mounted and every stateful
// component's data lives, matching infrastructure/cloud-init/k3s-node.yaml.tpl.
const DataDirectory = "/mnt/smallworlds-data"

// BootstrapInput is everything the node needs to bring itself up and converge on
// the selected GitOps Overlay.
//
// ProjectToken and ClusterSecrets are credential material. They reach the node
// through cloud-init, which the provider stores and which OpenTofu records in
// state — which is exactly why the state is treated as sensitive: owner-only,
// digest-only over the API, and never echoed into a diagnostic.
type BootstrapInput struct {
	NodeName       string
	Domain         string
	EnvExt         string
	ServerAddress  string
	ACMEEmail      string
	ProjectToken   string
	OverlayGitURL  string
	OverlayCommit  string
	ClusterSecrets string
	RecordNames    []string
}

// Validate rejects any input that could produce a malformed or injectable
// payload. Every value is interpolated into a YAML document and a shell script,
// so a newline or a quote in the wrong field is a code-execution boundary.
func (input BootstrapInput) Validate() error {
	if !safeNodeName.MatchString(input.NodeName) {
		return fmt.Errorf("%w: node name", ErrInvalidBootstrap)
	}
	if !safeHostname.MatchString(input.Domain) || !strings.Contains(input.Domain, ".") {
		return fmt.Errorf("%w: domain", ErrInvalidBootstrap)
	}
	if input.EnvExt != "" && (!strings.HasPrefix(input.EnvExt, ".") || !safeLabel.MatchString(strings.TrimPrefix(input.EnvExt, "."))) {
		return fmt.Errorf("%w: environment extension", ErrInvalidBootstrap)
	}
	// An empty address is the ordinary first-install case: the Primary IP does
	// not exist until OpenTofu creates it, so the node discovers its own address
	// at boot — exactly as the shared k3s-node template does.
	if input.ServerAddress != "" && !safeAddress.MatchString(input.ServerAddress) {
		return fmt.Errorf("%w: server address", ErrInvalidBootstrap)
	}
	// A Hetzner installation always serves a public domain, so it always uses
	// publicly trusted ACME certificates — and the DNS01 solver always needs a
	// project token. A self-signed fallback here would silently produce a
	// cluster whose certificates no browser accepts.
	if input.ACMEEmail == "" || !strings.Contains(input.ACMEEmail, "@") || strings.ContainsAny(input.ACMEEmail, "\r\n\"'`$\\") {
		return fmt.Errorf("%w: ACME email", ErrInvalidBootstrap)
	}
	if !safeProjectToken.MatchString(input.ProjectToken) {
		return fmt.Errorf("%w: project token", ErrInvalidBootstrap)
	}
	if !strings.HasPrefix(input.OverlayGitURL, "https://") || strings.ContainsAny(input.OverlayGitURL, " \r\n'\"`$\\") {
		return fmt.Errorf("%w: overlay repository", ErrInvalidBootstrap)
	}
	if !safeCommit.MatchString(input.OverlayCommit) {
		return fmt.Errorf("%w: overlay commit", ErrInvalidBootstrap)
	}
	if len(input.RecordNames) == 0 {
		return fmt.Errorf("%w: no service hostnames", ErrInvalidBootstrap)
	}
	for _, record := range input.RecordNames {
		if record != "@" && !safeLabel.MatchString(record) {
			return fmt.Errorf("%w: service hostname %q", ErrInvalidBootstrap, record)
		}
	}
	return nil
}

// RenderCloudInit produces the node's bootstrap payload.
//
// It implements the same contract as infrastructure/cloud-init/k3s-node.yaml.tpl
// — the ACME letsencrypt-prod issuer, the coredns-custom override, the
// /mnt/smallworlds-data layout, and the Argo CD root application — because a
// node the console provisions must be indistinguishable from one the repository's
// own Terraform provisions. It differs in one respect on purpose: it writes the
// readiness markers the launcher observes convergence through, and it pins the
// root application to the approved overlay commit rather than tracking HEAD, so
// what converges is what the Operator approved.
func RenderCloudInit(input BootstrapInput) (string, error) {
	if err := input.Validate(); err != nil {
		return "", err
	}
	var out strings.Builder
	out.WriteString(`#cloud-config
# Generated by the SmallWorlds Operator Console. Implements the same bootstrap
# contract as infrastructure/cloud-init/k3s-node.yaml.tpl.
package_update: true
packages:
  - curl
  - jq

swap:
  filename: /swap.img
  size: "8G"

write_files:
  - path: /etc/sysctl.d/99-kubernetes-cri.conf
    permissions: '0644'
    content: |
      fs.inotify.max_user_instances=8192
      fs.inotify.max_user_watches=524288

`)
	writeRootApplication(&out, input)
	writeClusterSecrets(&out, input)
	out.WriteString("runcmd:\n")
	writeNodeAddress(&out, input)
	writeStorage(&out)
	writeIssuer(&out, input)
	writeCoreDNS(&out, input)
	writeK3S(&out, input)
	writeClusterSecretsApply(&out, input)
	writeArgoCD(&out, input)
	writeTailscale(&out)
	return out.String(), nil
}

// writeRootApplication pins the Argo CD root application to the approved
// overlay commit. targetRevision is the commit, never HEAD: an overlay that
// advanced between approval and boot would otherwise deploy something the
// Operator never reviewed.
func writeRootApplication(out *strings.Builder, input BootstrapInput) {
	fmt.Fprintf(out, `  - path: /var/lib/smallworlds/argocd-root-app.yaml
    permissions: '0600'
    content: |
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: smallworlds-root
        namespace: argocd
        finalizers:
          - resources-finalizer.argocd.argoproj.io
      spec:
        project: default
        source:
          repoURL: '%s'
          targetRevision: '%s'
          path: .
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: argocd
        syncPolicy:
          retry:
            limit: 20
            backoff:
              duration: 15s
              factor: 2
              maxDuration: 5m
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true
            - SkipDryRunOnMissingResource=true

`, input.OverlayGitURL, input.OverlayCommit)
}

// writeClusterSecrets stages the operator-supplied Cluster Secrets with
// owner-only permissions. They are applied once k3s is up and the file is
// removed immediately afterwards, so the material does not linger on disk.
func writeClusterSecrets(out *strings.Builder, input BootstrapInput) {
	if strings.TrimSpace(input.ClusterSecrets) == "" {
		return
	}
	out.WriteString("  - path: /var/lib/smallworlds/cluster-secrets.yaml\n    permissions: '0600'\n    content: |\n")
	writeIndented(out, input.ClusterSecrets, "      ")
	out.WriteString("\n")
}

// writeNodeAddress resolves the address k3s binds to and the in-cluster
// resolver points at. On a first install the Primary IP does not exist until
// OpenTofu creates it, so the node discovers its own address; on a rebuild the
// approved address is already known and is used verbatim, which keeps a node
// that boots before its IP is attached from binding to the wrong one.
func writeNodeAddress(out *strings.Builder, input BootstrapInput) {
	out.WriteString("  - mkdir -p /etc/smallworlds /var/lib/smallworlds\n")
	if input.ServerAddress != "" {
		fmt.Fprintf(out, "  - echo %s > /etc/smallworlds/node-address\n\n", input.ServerAddress)
		return
	}
	out.WriteString("  - hostname -I | awk '{print $1}' > /etc/smallworlds/node-address\n\n")
}

func writeStorage(out *strings.Builder) {
	fmt.Fprintf(out, `  # Persistent volume: everything the community cannot recreate lives here and
  # survives the node being destroyed and rebuilt.
  - |
    set -eu
    VOLUME_DEVICE=$(lsblk -rpo 'NAME,MOUNTPOINT' | awk '$2=="" && $1 !~ /^\/dev\/(sda|sr)/ {print $1}' | head -n1)
    if [ -n "$VOLUME_DEVICE" ]; then
      MOUNT_DIR=$(lsblk -rpo 'NAME,MOUNTPOINT' | awk -v dev="$VOLUME_DEVICE" '$1==dev {print $2}' | head -n1)
      if [ -z "$MOUNT_DIR" ]; then MOUNT_DIR=%[1]s ; mkdir -p "$MOUNT_DIR" ; mount "$VOLUME_DEVICE" "$MOUNT_DIR" ; fi
      ln -sfn "$MOUNT_DIR" %[1]s
    fi
    mkdir -p %[1]s/garage %[1]s/immich-library %[1]s/k3s
    mkdir -p /etc/smallworlds /var/lib/smallworlds
    chmod 0700 /var/lib/smallworlds

  # Never inherit a snapshot's cluster identity: a fresh node that joined the
  # image builder's cluster would serve another installation's data.
  - rm -rf /var/lib/rancher/k3s/server /etc/rancher/k3s /etc/rancher/node
  - if [ -d /var/lib/rancher/k3s ] && [ ! -L /var/lib/rancher/k3s ]; then cp -a /var/lib/rancher/k3s/* %[1]s/k3s/ ; rm -rf /var/lib/rancher/k3s ; fi
  - mkdir -p /var/lib/rancher
  - ln -sfn %[1]s/k3s /var/lib/rancher/k3s
  - sysctl --system
  - mkdir -p /var/lib/rancher/k3s/server/manifests

`, DataDirectory)
}

// writeIssuer installs the publicly trusted ACME issuer and the DNS01 solver
// credential. The secret is written straight into the k3s manifest directory
// rather than through Argo CD so it exists before the first ACME order fires.
func writeIssuer(out *strings.Builder, input BootstrapInput) {
	fmt.Fprintf(out, `  - |
    cat > /var/lib/rancher/k3s/server/manifests/letsencrypt-prod.yaml <<'ISSUER'
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: letsencrypt-prod
    spec:
      acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: "%s"
        privateKeySecretRef:
          name: letsencrypt-prod
        solvers:
        - dns01:
            webhook:
              groupName: acme.hetzner.com
              solverName: hetzner
              config:
                tokenSecretKeyRef:
                  name: hetzner
                  key: token
    ISSUER
  - |
    umask 077
    cat > /var/lib/rancher/k3s/server/manifests/cert-manager-webhook-hetzner-secret.yaml <<'HETZNERSECRET'
    apiVersion: v1
    kind: Secret
    metadata:
      name: hetzner
      namespace: cert-manager
    type: Opaque
    stringData:
      token: "%s"
    HETZNERSECRET

`, input.ACMEEmail, input.ProjectToken)
}

// writeCoreDNS points in-cluster resolution of the installation's own hostnames
// at this node. Without it pods resolve the app domains through public DNS,
// which during a rebuild still points at the previous server.
func writeCoreDNS(out *strings.Builder, input BootstrapInput) {
	hosts := make([]string, 0, len(input.RecordNames))
	for _, record := range input.RecordNames {
		if record == "@" {
			hosts = append(hosts, input.Domain)
			continue
		}
		hosts = append(hosts, record+input.EnvExt+"."+input.Domain)
	}
	sort.Strings(hosts)
	// The heredoc is unquoted so the node's own address is substituted; every
	// other value is already validated and contains no shell metacharacters.
	fmt.Fprintf(out, `  - |
    NODE_ADDRESS=$(cat /etc/smallworlds/node-address)
    cat > /var/lib/rancher/k3s/server/manifests/coredns-custom.yaml <<COREDNS
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: coredns-custom
      namespace: kube-system
    data:
      smallworlds.server: |
        %s:53 {
          hosts {
            $NODE_ADDRESS %s
            fallthrough
          }
          forward . /etc/resolv.conf
        }
    COREDNS

`, input.Domain, strings.Join(hosts, " "))
}

func writeK3S(out *strings.Builder, input BootstrapInput) {
	fmt.Fprintf(out, `  # k3s. An explicit --node-name keeps a snapshot boot from registering a ghost
  # node under the image builder's transient hostname.
  - |
    curl -sfL https://get.k3s.io | sh -s - server --cluster-init --node-ip=$(cat /etc/smallworlds/node-address) --node-name=%s --disable traefik --kubelet-arg=registry-qps=50 --kubelet-arg=registry-burst=100
  - export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
  - until k3s kubectl get nodes | grep -v NotReady | grep -q Ready; do sleep 5; done
  - touch %s

`, input.NodeName, K3SReadyMarker)
}

// writeClusterSecretsApply applies the operator's Cluster Secrets before Argo CD
// starts reconciling, so an application whose secret is missing never reaches a
// crash loop the operator then has to diagnose. The file is removed immediately.
func writeClusterSecretsApply(out *strings.Builder, input BootstrapInput) {
	if strings.TrimSpace(input.ClusterSecrets) == "" {
		return
	}
	out.WriteString(`  - k3s kubectl apply -f /var/lib/smallworlds/cluster-secrets.yaml
  - shred -u /var/lib/smallworlds/cluster-secrets.yaml 2>/dev/null || rm -f /var/lib/smallworlds/cluster-secrets.yaml

`)
}

func writeArgoCD(out *strings.Builder, input BootstrapInput) {
	fmt.Fprintf(out, `  # Argo CD, then the root application pinned to the approved overlay commit.
  - k3s kubectl create namespace argocd || true
  - k3s kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml --server-side --force-conflicts
  - |
    cat > /tmp/argocd-cm-patch.yaml <<'ARGOCM'
    data:
      kustomize.buildOptions: "--enable-helm"
      server.insecure: "true"
      resource.customizations.health.argoproj.io_Application: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs
    ARGOCM
  - k3s kubectl patch cm/argocd-cm -n argocd --type=merge --patch-file /tmp/argocd-cm-patch.yaml
  # server.insecure is only honoured in argocd-cmd-params-cm; without it
  # argocd-server redirects Traefik's plain-HTTP upstream traffic back to https
  # forever and the console never loads.
  - k3s kubectl patch cm/argocd-cmd-params-cm -n argocd --type=merge -p '{"data":{"server.insecure":"true"}}'
  - k3s kubectl -n argocd rollout restart deployment argocd-server
  - k3s kubectl -n argocd rollout status deployment/argocd-server --timeout=600s
  - touch %s
  - k3s kubectl apply -f /var/lib/smallworlds/argocd-root-app.yaml
  - touch %s

`, ArgoCDReadyMarker, OverlayReadyMarker)
}

// writeTailscale installs the client only. Joining the tailnet needs a preauth
// key that exists only after Argo CD has deployed Headscale, so enrolment stays
// a deliberate later step of the private handoff.
func writeTailscale(out *strings.Builder) {
	out.WriteString("  - curl -fsSL https://tailscale.com/install.sh | sh\n")
}

func writeIndented(out *strings.Builder, contents, indent string) {
	for _, line := range strings.Split(strings.TrimRight(contents, "\n"), "\n") {
		out.WriteString(indent)
		out.WriteString(line)
		out.WriteString("\n")
	}
}
