import type { Locale } from './i18n';

const en = {
  eyebrow: 'Recovery authority',
  preserveTitle: 'Shut it down, but keep the data',
  preserveDescription: 'Checks what actually belongs to this installation, then stops and removes only the machines and the running apps. Your data stays where it is. Shared DNS zones, your settings repository, and anything that cannot be proven to belong here are left alone. Only the person holding recovery authority (Lifecycle Authority) can do this.',
  preservePlan: 'Check what would be removed',
  planDigest: 'Plan fingerprint (digest)',
  expectedDowntime: 'How long it will be offline',
  recoveryPath: 'How to bring it back',
  retainedData: 'What is kept',
  noneDeclared: 'Nothing listed',
  continuingCost: 'What you will still be billed for',
  none: 'Nothing',
  deletionBlocked: 'Cannot remove this yet:',
  reinspectPlan: 'Check again',
  approvePreserve: 'Approve — shut down and keep the data',
  run: 'Run',
  at: 'at',
  resume: 'Check again and continue',
  forgetDescription: 'This only makes this computer forget the installation. Nothing on the server, in your cluster, in DNS, in your settings repository, or in your data is changed or deleted. The cluster keeps running.',
  forget: 'Forget it on this computer',
  forgetConfirm: 'Forget “{name}” on this computer? The cluster keeps running and nothing on the server changes.',
  irreversible: 'Recovery authority · cannot be undone',
  fullTitle: 'Delete everything, permanently',
  fullDescription: 'Checked separately, and it does not stop at the machines: this permanently deletes your data as well. It removes only what can be proven to belong to this installation — shared DNS zones, your settings repository, and anything of unclear ownership are left alone. There is no undo. Only the person holding recovery authority (Lifecycle Authority) can do this.',
  fullPlan: 'Check my backups and show what would be deleted',
  backupFreshness: 'How recent your backup is',
  offsitePoints: 'Backup copies held elsewhere',
  noneObserved: 'None found',
  recoveryBundle: 'Recovery Bundle',
  protectionInsufficient: 'Your backups are not good enough to do this safely.',
  protectionMissing: 'At least one of these is missing: a recent backup, a copy held somewhere else, or a Recovery Bundle.',
  overrideAccept: 'I hold recovery authority for this cluster, and I accept that this data will be gone despite the gap in protection.',
  overrideReason: 'Why you are going ahead anyway',
  irreversibleConsequences: 'What will be gone for good:',
  typedConfirmationPrompt: 'Type this exactly, to confirm you mean to delete it all',
  typedConfirmation: 'Typed confirmation for permanent deletion',
  discardReinspect: 'Discard this plan and check again',
  typeConfirm: 'Permanently delete everything',
  resumeScope: 'Check again and continue what was approved',
  exportRecord: 'Save a record of what happened'
} as const;

const de: Record<keyof typeof en, string> = {
  eyebrow: 'Wiederherstellungsbefugnis',
  preserveTitle: 'Stilllegen, aber die Daten behalten',
  preserveDescription: 'Prüft, was wirklich zu dieser Installation gehört, und stoppt und entfernt dann nur die Rechner und die laufenden Anwendungen. Ihre Daten bleiben, wo sie sind. Gemeinsame DNS-Zonen, Ihr Einstellungs-Repository und alles, dessen Zugehörigkeit sich nicht nachweisen lässt, bleiben unangetastet. Das kann nur, wer die Wiederherstellungsbefugnis trägt (Lifecycle Authority).',
  preservePlan: 'Prüfen, was entfernt würde',
  planDigest: 'Plan-Fingerabdruck (Digest)',
  expectedDowntime: 'Wie lange es offline sein wird',
  recoveryPath: 'Wie Sie es zurückholen',
  retainedData: 'Was erhalten bleibt',
  noneDeclared: 'Nichts aufgeführt',
  continuingCost: 'Wofür Sie weiterhin bezahlen',
  none: 'Nichts',
  deletionBlocked: 'Das lässt sich noch nicht entfernen:',
  reinspectPlan: 'Erneut prüfen',
  approvePreserve: 'Genehmigen — stilllegen und Daten behalten',
  run: 'Ausführung',
  at: 'bei',
  resume: 'Erneut prüfen und fortsetzen',
  forgetDescription: 'Damit vergisst nur dieser Computer die Installation. Auf dem Server, im Cluster, im DNS, in Ihrem Einstellungs-Repository und an Ihren Daten ändert sich nichts. Der Cluster läuft weiter.',
  forget: 'Auf diesem Computer vergessen',
  forgetConfirm: '„{name}“ auf diesem Computer vergessen? Der Cluster läuft weiter, und auf dem Server ändert sich nichts.',
  irreversible: 'Wiederherstellungsbefugnis · nicht umkehrbar',
  fullTitle: 'Alles endgültig löschen',
  fullDescription: 'Wird gesondert geprüft und hört nicht bei den Rechnern auf: Hierbei werden auch Ihre Daten endgültig gelöscht. Entfernt wird nur, was sich nachweislich dieser Installation zuordnen lässt — gemeinsame DNS-Zonen, Ihr Einstellungs-Repository und alles mit unklarer Zugehörigkeit bleiben unangetastet. Es gibt kein Zurück. Das kann nur, wer die Wiederherstellungsbefugnis trägt (Lifecycle Authority).',
  fullPlan: 'Sicherungen prüfen und anzeigen, was gelöscht würde',
  backupFreshness: 'Wie aktuell Ihre Sicherung ist',
  offsitePoints: 'Sicherungskopien an anderen Orten',
  noneObserved: 'Keine gefunden',
  recoveryBundle: 'Wiederherstellungsbündel',
  protectionInsufficient: 'Ihre Sicherungen reichen nicht aus, um das gefahrlos zu tun.',
  protectionMissing: 'Mindestens eines davon fehlt: eine aktuelle Sicherung, eine Kopie an einem anderen Ort oder ein Wiederherstellungsbündel.',
  overrideAccept: 'Ich trage die Wiederherstellungsbefugnis für diesen Cluster und akzeptiere, dass diese Daten trotz der Schutzlücke verloren sein werden.',
  overrideReason: 'Warum Sie es trotzdem tun',
  irreversibleConsequences: 'Was endgültig verloren geht:',
  typedConfirmationPrompt: 'Tippen Sie genau das ab, um zu bestätigen, dass Sie wirklich alles löschen wollen',
  typedConfirmation: 'Eingabebestätigung für das endgültige Löschen',
  discardReinspect: 'Diesen Plan verwerfen und erneut prüfen',
  typeConfirm: 'Alles endgültig löschen',
  resumeScope: 'Erneut prüfen und den genehmigten Umfang fortsetzen',
  exportRecord: 'Einen Nachweis des Ablaufs speichern'
};

export type DecommissionCopyKey = keyof typeof en;

export function decommissionCopy(locale: Locale, key: DecommissionCopyKey): string {
  return (locale === 'de' ? de : en)[key];
}
