import type { Locale } from './i18n';

const en = {
  eyebrow: 'Lifecycle authority',
  preserveTitle: 'Preserve-data decommission',
  preserveDescription: 'Freshly inspect provider and cluster identity, then stop or remove only proven profile-owned compute and workloads. Persistent data, shared DNS zones, GitOps overlay, and unknown resources are retained.',
  preservePlan: 'Inspect and prepare preserve-data plan',
  planDigest: 'Plan digest',
  expectedDowntime: 'Expected downtime',
  recoveryPath: 'Recovery path',
  retainedData: 'Retained data',
  noneDeclared: 'None declared',
  continuingCost: 'Continuing provider cost',
  none: 'None',
  deletionBlocked: 'Deletion blocked:',
  reinspectPlan: 'Reinspect and re-plan',
  approvePreserve: 'Approve preserve-data decommission',
  run: 'Run',
  at: 'at',
  resume: 'Reinspect and resume',
  forgetDescription: 'Forget profile only removes this Launcher Host’s local reference. It performs no provider, cluster, DNS, overlay, or data mutation.',
  forget: 'Forget local Cluster Profile',
  forgetConfirm: 'Forget local profile “{name}”? This does not change any cluster or provider resource.',
  irreversible: 'Lifecycle authority · irreversible',
  fullTitle: 'Full decommission',
  fullDescription: 'This separately inspected journey permanently removes only resources proven to belong to this Cluster Profile, including persistent data. Shared DNS zones, the GitOps Overlay, and anything with unknown ownership remain retained.',
  fullPlan: 'Inspect protection and prepare full-decommission plan',
  backupFreshness: 'Backup freshness',
  offsitePoints: 'Offsite Recovery Points',
  noneObserved: 'None observed',
  recoveryBundle: 'Recovery Bundle',
  protectionInsufficient: 'Protection is insufficient.',
  protectionMissing: 'A current backup, offsite Recovery Point, or Recovery Bundle is missing.',
  overrideAccept: 'I am the Lifecycle Authority and explicitly accept deletion despite this protection gap.',
  overrideReason: 'Reason for informed override',
  irreversibleConsequences: 'Irreversible consequences:',
  typedConfirmation: 'Full decommission typed confirmation',
  discardReinspect: 'Discard and reinspect',
  typeConfirm: 'Type-confirm and permanently decommission',
  resumeScope: 'Reinspect and resume the approved scope',
  exportRecord: 'Export final redacted Activity Record'
} as const;

const de: Record<keyof typeof en, string> = {
  eyebrow: 'Lebenszyklusverantwortung',
  preserveTitle: 'Stilllegung mit Datenerhalt',
  preserveDescription: 'Prüfen Sie Anbieter- und Clusteridentität erneut und stoppen oder entfernen Sie nur nachweislich diesem Profil gehörende Rechenressourcen und Workloads. Dauerhafte Daten, gemeinsame DNS-Zonen, das GitOps-Overlay und Ressourcen mit unbekannter Zuordnung bleiben erhalten.',
  preservePlan: 'Stilllegungsplan mit Datenerhalt prüfen und vorbereiten',
  planDigest: 'Plan-Prüfsumme',
  expectedDowntime: 'Erwartete Ausfallzeit',
  recoveryPath: 'Wiederherstellungsweg',
  retainedData: 'Erhaltene Daten',
  noneDeclared: 'Keine angegeben',
  continuingCost: 'Fortlaufende Anbieterkosten',
  none: 'Keine',
  deletionBlocked: 'Löschen blockiert:',
  reinspectPlan: 'Erneut prüfen und planen',
  approvePreserve: 'Stilllegung mit Datenerhalt genehmigen',
  run: 'Ausführung',
  at: 'bei',
  resume: 'Erneut prüfen und fortsetzen',
  forgetDescription: 'Profil vergessen entfernt nur die lokale Referenz dieses Launcher-Hosts. Anbieter, Cluster, DNS, Overlay und Daten werden nicht verändert.',
  forget: 'Lokales Clusterprofil vergessen',
  forgetConfirm: 'Lokales Profil „{name}“ vergessen? Dies verändert keine Cluster- oder Anbieterressource.',
  irreversible: 'Lebenszyklusverantwortung · unumkehrbar',
  fullTitle: 'Vollständige Stilllegung',
  fullDescription: 'Diese separat geprüfte Reise entfernt dauerhaft nur Ressourcen, die nachweislich zu diesem Clusterprofil gehören, einschließlich dauerhafter Daten. Gemeinsame DNS-Zonen, das GitOps-Overlay und alles mit unbekannter Zuordnung bleiben erhalten.',
  fullPlan: 'Schutz prüfen und vollständigen Stilllegungsplan vorbereiten',
  backupFreshness: 'Aktualität der Sicherung',
  offsitePoints: 'Externe Wiederherstellungspunkte',
  noneObserved: 'Keine beobachtet',
  recoveryBundle: 'Wiederherstellungsbündel',
  protectionInsufficient: 'Der Schutz ist unzureichend.',
  protectionMissing: 'Eine aktuelle Sicherung, ein externer Wiederherstellungspunkt oder ein Wiederherstellungsbündel fehlt.',
  overrideAccept: 'Ich trage die Lebenszyklusverantwortung und akzeptiere das Löschen trotz dieser Schutzlücke ausdrücklich.',
  overrideReason: 'Grund für die informierte Ausnahme',
  irreversibleConsequences: 'Unumkehrbare Folgen:',
  typedConfirmation: 'Eingabebestätigung für die vollständige Stilllegung',
  discardReinspect: 'Verwerfen und erneut prüfen',
  typeConfirm: 'Eingabe bestätigen und dauerhaft stilllegen',
  resumeScope: 'Erneut prüfen und den genehmigten Umfang fortsetzen',
  exportRecord: 'Abschließenden redigierten Aktivitätsnachweis exportieren'
};

export type DecommissionCopyKey = keyof typeof en;

export function decommissionCopy(locale: Locale, key: DecommissionCopyKey): string {
  return (locale === 'de' ? de : en)[key];
}
