postgres:
  local_setup: false
redis:
  local_setup: false
minio:
  local_setup: false
rabbitmq:
  local_setup: false

ingress:
  enabled: true
  appHost: "plan.smallworlds.network"
  ingressClass: "nginx"
  ingress_annotations: {}
  tls:
    - hosts:
        - plan.smallworlds.network
      secretName: plane-tls

# We are using Kustomize patches in kustomization.yaml to inject our custom
# OIDC, Postgres, and Redis environment variables securely into all Deployments.
