apiVersion: batch/v1
kind: Job
metadata:
  name: forgejo-secret-init
  namespace: forgejo
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      serviceAccountName: setup-sa
      containers:
        - name: secret-gen
          image: bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              set -e
              if ! kubectl get secret forgejo-admin-creds -n forgejo >/dev/null 2>&1; then
                echo "Generating Forgejo password..."
                PASSWORD=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)
                
                kubectl create secret generic forgejo-admin-creds -n forgejo \
                  --from-literal=password="$PASSWORD"
              else
                echo "forgejo-admin-creds already exists, skipping."
              fi
      restartPolicy: OnFailure
