apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo

bases:
  - ../../bases/setup-rbac
  - ../../bases/redis
  - ../../bases/cnpg-cluster
  - ../../bases/garage-init-job
  - ../../bases/keycloak-client-job

resources:
  - oidc-config-job.yaml
  - forgejo-secret-init-job.yaml

patches:
  - target:
      kind: Job
      name: keycloak-client-init
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: REDIRECT_URIS
            value: '["https://git.smallworlds.network/user/oauth2/Keycloak/callback"]'

helmCharts:
  - name: forgejo
    repo: oci://codeberg.org/forgejo-contrib
    releaseName: forgejo
    version: 1.1.7
    valuesFile: values.yaml
