apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bulwark-ingress
  namespace: bulwark
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Webmail"
    gethomepage.dev/description: "Bulwark"
    gethomepage.dev/group: "Applications"
    gethomepage.dev/icon: "bulwark.png"
    gethomepage.dev/pod-selector: "app=bulwark"
spec:
  rules:
    - host: webmail.smallworlds.network
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bulwark
                port:
                  name: http
  tls:
    - hosts:
        - webmail.smallworlds.network
      secretName: bulwark-tls
