apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - roundcube-pvc.yaml
  - roundcube-secret.yaml
  - roundcube-oauth-config.yaml
  - roundcube-deployment.yaml
  - roundcube-ingress.yaml
