apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - roundcube-pvc.yaml
  - setup-rbac.yaml
  - keycloak-client-job.yaml
  - roundcube-oauth-config.yaml
  - roundcube-deployment.yaml
  - roundcube-ingress.yaml
