apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "ArgoCD"
    gethomepage.dev/description: "GitOps Continuous Delivery"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "argocd.png"
spec:
  rules:
    - host: deploy.smallworlds.network
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
  tls:
    - hosts:
        - deploy.smallworlds.network
      secretName: argocd-server-tls
