apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  name: cloudnative-pg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://cloudnative-pg.github.io/charts'
    targetRevision: 0.29.0
    chart: cloudnative-pg
    helm:
      values: |
        # Default values for cloudnative-pg operator are usually sufficient
        config:
          ENABLE_METRICS: "true"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
