apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusterissuer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/stephan271/smallworlds.git'
    targetRevision: HEAD
    path: 00-letsgo/infrastructure/kubernetes/components/clusterissuer
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
