apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  name: garage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://datahub-local.github.io/garage-helm'
    targetRevision: 0.7.1
    chart: garage
    helm:
      values: |
        deployment:
          replicaCount: 1
        garage:
          replicationFactor: "1"
          secret:
            create: false
            name: "garage-auth-secret"
        persistence:
          enabled: true
          size: 120Gi
          storageClass: hetzner-local
        service:
          s3:
            type: ClusterIP
            port: 3900
          api:
            type: ClusterIP
            port: 3901
          web:
            type: ClusterIP
            port: 3902
        ingress:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: garage-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
