apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: stalwart
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/stephan271/smallworlds.git'
    targetRevision: HEAD
    path: infrastructure/kubernetes/tenants/stalwart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: stalwart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
