apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    targetRevision: "34.4.1"
    chart: traefik
    helm:
      values: |
        ports:
          web:
            redirections:
              entryPoint:
                to: websecure
                scheme: https
          websecure:
            tls:
              enabled: true
        ingressRoute:
          dashboard:
            enabled: false
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true
        service:
          type: LoadBalancer
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
