apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: excalidraw
  namespace: excalidraw
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Whiteboard"
    gethomepage.dev/description: "Excalidraw"
    gethomepage.dev/group: "Applications"
    gethomepage.dev/icon: "excalidraw.png"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=excalidraw"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - whiteboard.smallworlds.network
      secretName: excalidraw-tls
  rules:
    - host: whiteboard.smallworlds.network
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: excalidraw
                port:
                  number: 80
