http:
  relativePath: "/"

command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--http-port=8080"
  - "--http-relative-path=/"
  - "--hostname=identity.smallworlds.network"
  - "--spi-events-listener-jboss-logging-success-level=info"
  - "--spi-events-listener-jboss-logging-error-level=warn"
  - "--features=recovery-codes"

extraEnv: |
  - name: JAVA_OPTS_APPEND
    value: "-Djgroups.dns.query=keycloak-headless -Dmail.smtp.ssl.trust=stalwart-mail.stalwart.svc.cluster.local"
  - name: KC_DB
    value: postgres
  - name: KC_DB_URL_HOST
    value: keycloak-db-rw
  - name: KC_DB_URL_DATABASE
    value: keycloak
  - name: KC_DB_USERNAME
    value: keycloak
  - name: KC_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-db-app
        key: password
  - name: KEYCLOAK_ADMIN
    value: "admin"
  - name: KEYCLOAK_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-admin-creds
        key: admin-password
  - name: STALWART_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-stalwart-secret
        key: password
        optional: true
  - name: KC_SMTP_HOST
    value: "stalwart-mail.stalwart.svc.cluster.local"
  - name: KC_SMTP_PORT
    value: "25"
  - name: KC_SMTP_FROM
    value: "auth@smallworlds.network"
  - name: KC_SMTP_AUTH
    value: "false"
  - name: KC_SMTP_STARTTLS
    value: "false"
  - name: KC_SMTP_USER
    value: "admin"
  - name: KC_SMTP_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-stalwart-secret
        key: password
        optional: true

  - name: KC_PROXY
    value: "edge"
  - name: KC_PROXY_HEADERS
    value: "xforwarded"
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: KC_HOSTNAME_STRICT
    value: "false"
  - name: KC_HOSTNAME_STRICT_HTTPS
    value: "false"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: keycloak-keycloak-redirect@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Auth"
    gethomepage.dev/description: "Keycloak"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "keycloak.png"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=keycloakx"
  rules:
    - host: identity.smallworlds.network
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - identity.smallworlds.network
      secretName: keycloak-tls

extraVolumes: |
  - name: realm-config
    configMap:
      name: keycloak-realm-config
  - name: spi-volume
    configMap:
      name: keycloak-spi-config
extraVolumeMounts: |
  - name: realm-config
    mountPath: "/opt/keycloak/data/realm-config/smallworlds-realm.json"
    subPath: "smallworlds-realm.json"
    readOnly: true
  - name: spi-volume
    mountPath: "/opt/keycloak/providers/action-token-generator.jar"
    subPath: "action-token-generator.jar"
    readOnly: true
