apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smallworlds-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # REPLACE this with the actual URL of your citizennet git repository
    repoURL: 'https://github.com/stephan271/smallworlds.git'
    targetRevision: HEAD
    path: infrastructure/kubernetes
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    retry:
      limit: 20
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
