apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  - cnpg-cluster.yaml
  - redis.yaml
  - oidc-config-job.yaml
  - garage-init-job.yaml
  - nextcloud-secret-init-job.yaml
  - keycloak-client-job.yaml
  - setup-rbac.yaml

helmCharts:
  - name: nextcloud
    repo: https://nextcloud.github.io/helm/
    releaseName: nextcloud
    version: 9.0.2
    valuesFile: values.yaml
