apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud

bases:
  - ../../bases/setup-rbac
  - ../../bases/garage-init-job
  - ../../bases/keycloak-client-job

resources:
  - redis.yaml
  - cnpg-cluster.yaml
  - oidc-config-job.yaml
  - nextcloud-secret-init-job.yaml

patches:
  - target:
      kind: ClusterRoleBinding
      name: setup-binding
    patch: |-
      - op: replace
        path: /metadata/name
        value: setup-binding-nextcloud
  - target:
      kind: Job
      name: keycloak-client-init
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: REDIRECT_URIS
            value: '["https://files.smallworlds.network/apps/user_oidc/code", "https://files.smallworlds.network/*"]'

helmCharts:
  - name: nextcloud
    repo: https://nextcloud.github.io/helm/
    releaseName: nextcloud
    version: 9.2.0
    valuesFile: values.yaml
