apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextcloud-setup-sa
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/hook: PreSync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nextcloud-setup-role
  annotations:
    argocd.argoproj.io/hook: PreSync
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "patch", "apply"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nextcloud-setup-binding
  annotations:
    argocd.argoproj.io/hook: PreSync
subjects:
  - kind: ServiceAccount
    name: nextcloud-setup-sa
    namespace: nextcloud
roleRef:
  kind: ClusterRole
  name: nextcloud-setup-role
  apiGroup: rbac.authorization.k8s.io
