apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cnpg-cluster.yaml
  - stalwart-deployment.yaml
  - stalwart-init-job.yaml
  - mail-provisioner-deployment.yaml
  - stalwart-ingress.yaml

